---
- name: install certbot
  apt:
    name: certbot
    state: present

- name: ensure certbot well-known path exists
  file:
    path: '{{webroot}}/.well-known'
    state: directory

- name: test if Certbot has been initialized
  stat:
    path: /etc/letsencrypt/live/w3c-test.org/fullchain.pem
  register: cert_file

- name: intialize certbot
  command: >
    certbot
      certonly
      --webroot
      --agree-tos
      --non-interactive
      {{ (env == 'production') | ternary('', '--test-cert') }}
      --email {{letsencrypt_email}}
      --webroot-path {{webroot}}
      --domain w3c-test.org
      --domain not-w3c-test.org
      --domain xn--lve-6lad.w3c-test.org
      --domain xn--lve-6lad.not-w3c-test.org
      --domain xn--n8j6ds53lwwkrqhv28a.w3c-test.org
      --domain xn--n8j6ds53lwwkrqhv28a.not-w3c-test.org
      --domain www1.w3c-test.org
      --domain www1.not-w3c-test.org
      --domain www2.w3c-test.org
      --domain www2.not-w3c-test.org
      --domain www.w3c-test.org
      --domain www.not-w3c-test.org
  when: cert_file.stat.exists == False

- name: Add cron job for cert renewal
  cron:
    name: Certbot automatic renewal.
    job: '/usr/bin/certbot renew --quiet --no-self-upgrade && systemctl restart wpt'
    minute: 0
    hour: 23
